# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CXSwiftStudy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic 

    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'


  use_frameworks!

  # Pods for CXSwiftStudy

end
